### PR TITLE
Create a grid based framework

### PR DESCRIPTION
**Pull request by fegzycole**
#### What does this PR do?
Creates a grid based framework which can be used to create responsive layouts.

#### How should this be manually tested?
My coding partner and I cloned [the odin project](https://www.theodinproject.com/),

Our Implementation with the custom Grid based framework can be found [Here](https://fegzycole.github.io/Grid-Based-Framework/)

### CODE REVIEW

**Review by izaiasneto4 — CHANGES_REQUESTED** [review]
### Hello Folks! Very good work so far with the framework and TOP clone! 👍️ There are just a few more tweaks that you need to do finally finish it, check below :arrow_down: :

- [ ] Your margins classes should span from 0 rem to 1 rem - currently from 0 rem to 3 rem

- [ ] Your paddings should span from 0 rem to 1 rem - currently from 0 rem to 3 rem

- [ ] The CSS framework file needs to define separate classes to change the position property of an element to relative, absolute or fixed

- [ ] You need a class in the framework to mark the display property as hidden 

- [ ] The framework CSS file has to define separate classes for border-top, bottom, left, right, all border

- [ ] The border classes should span from 0 to 1rem

- [ ] There should be a class for making box round

- [ ] The border should have a class defined to transform a box into a circle

#### That's it! Just a few more steps to reach the finish line of the project :smile: . I must say that your clone looks amazing and I am very impressed :nerd_face:   Nice job! 

### When finished, please submit the project for a new code review. Let's do this :muscle:. Good luck :crossed_fingers: 

#### TSE: Izaias Neto

**Comment by fegzycole** [comment]
Thank you for your feedback @izaiasneto4 

We have added more classes to the framework.

However, the margin and padding classes still span from 0rem to 3rem, this is because there wasn't any project-specific instruction for the spacing, and we believe that we are at liberty to use our discretion.

Best regards

**Comment by trox115** [comment]
### **Status:** Approved :+1: 
Hi @fegzycole  and @bafiam , it's very nice to meet you :handshake: . 
Awesome job implementing the changes asked by the last TSE, guys. 
You made a great work, you should be happy. 
Keep up the good work. 

Congratulations once again :tada: , 
You may now submit your project and go to the next one :muscle: .
_**António Fernandes**_

**Comment by bafiam** [comment]
@trox115, yeah, thanks for your encouraging and timely feedback, it means alot.

Best regards

**Pull request merged**
